# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# copy source
COPY . .

# compile TypeScript using project configuration
RUN npx tsc

# expose CSV file server port
EXPOSE 3001

# start MCP server
CMD ["node", "dist/ratespot_mcp_server.js"]
